config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :listings do
  resources :orders, only: [:new, :create]
  end
  
  
  get 'pages/about'

  get 'pages/contact'
  
  get 'seller' => "listings#seller"
  
  get 'sales' => "orders#sales"
  
  get 'purchases' => "orders#purchases"
  
  resources :categories
  
  root 'listings#index'

end

app/views/layouts/_footer.html.erb
<p><span style="color:#FF0066">Copyright 2016 Talia's Closet</span></p>

</br>
</br>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Talia's Closet</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
        <!--<li><a href="/pages/about">About <span class="sr-only">(current)</span></a></li> -->
        <!--<li><a href="/pages/contact">Contact</a></li> -->
        
        
      
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
        <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Listings" %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
        
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        
        
        
        <% if user_signed_in? %>
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                Seller Account <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><%= link_to "Manage Listings", seller_path %></li>
               <li><%= link_to "Sales History", sales_path %></li>
             </ul>
          </li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                <%= current_user.username %> <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><%= link_to "Purchase History", purchases_path %></li>
               <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
               <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
             </ul>
          </li>
         
        <% else %>
        
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
         <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
       
         
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CLOTHING <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
           
            <li><a href="#">Separated link</a></li>
            
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PLAYTIME <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            
            <li><a href="#">Separated link</a></li>
            
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ON THE GO <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
           
            <li><a href="#">Separated link</a></li>
            
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">BEDTIME <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            
            <li><a href="#">Separated link</a></li>
            
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">NURSING <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
           
            <li><a href="#">Separated link</a></li>
            
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DECOR AND KEEPSAKES <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</nav>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Talia's Closet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  
  
<%= render'layouts/header' %>
  
<div class="container">
    
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  
   

  <%= yield %>

<%= render 'layouts/footer' %>
</div>

</body>
</html>